chore: temporarily disable CI/CD

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,126 +1,129 @@
-stages:
-  - lint
-  - test
-  - build
-  - deploy
+# stages:
+#   - lint
+#   - test
+#   - build
+#   - deploy
 
-.go_default:
-  image: golang:1.25-alpine
-  interruptible: true
-  cache:
-    key: go-mod
-    paths:
-      - /go/pkg/mod
-      - ~/.cache/go-build
-  before_script:
-    - go version
+# .go_default:
+#   image: golang:1.25-alpine
+#   interruptible: true
+#   cache:
+#     key: go-mod
+#     paths:
+#       - /go/pkg/mod
+#       - ~/.cache/go-build
+#   before_script:
+#     - go version
 
-default:
-  interruptible: true
-  retry:
-    max: 1
-    when:
-      - runner_system_failure
-      - stuck_or_timeout_failure
+# default:
+#   interruptible: true
+#   retry:
+#     max: 1
+#     when:
+#       - runner_system_failure
+#       - stuck_or_timeout_failure
 
-# -------------------------
-# Lint
-# -------------------------
-lint:
-  extends: .go_default
-  stage: lint
-  script:
-    - echo "Checking code..."
-    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
-    - golangci-lint run --timeout=5m
-    - echo "No lint issues found."
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-    - if: $CI_COMMIT_BRANCH
+# # -------------------------
+# # Lint
+# # -------------------------
+# lint:
+#   extends: .go_default
+#   stage: lint
+#   script:
+#     - echo "Checking code..."
+#     - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
+#     - golangci-lint run --timeout=5m
+#     - echo "No lint issues found."
+#   rules:
+#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+#     - if: $CI_COMMIT_BRANCH
 
-# -------------------------
-# Unit Tests
-# -------------------------
-unit_test:
-  extends: .go_default
-  stage: test
-  script:
-    - echo "Running experiment result..."
-    - go test -v ./internal/features/...
-    - echo "All test passed."
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-    - if: $CI_COMMIT_BRANCH
+# # -------------------------
+# # Unit Tests
+# # -------------------------
+# unit_test:
+#   extends: .go_default
+#   stage: test
+#   script:
+#     - echo "Running experiment result..."
+#     - go test -v ./internal/features/...
+#     - echo "All test passed."
+#   rules:
+#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+#     - if: $CI_COMMIT_BRANCH
 
-# -------------------------
-# Build
-# -------------------------
-build:
-  extends: .go_default
-  stage: build
-  script:
-    - mkdir -p build
-    - GOOS=linux GOARCH=amd64 go build -o build/noheir-api.new ./cmd/main.go
-  artifacts:
-    paths:
-      - build/noheir-api.new
-    expire_in: 7 days
-  rules:
-    - if: $CI_COMMIT_BRANCH == "main"
+# # -------------------------
+# # Build
+# # -------------------------
+# build:
+#   extends: .go_default
+#   stage: build
+#   script:
+#     - mkdir -p build
+#     #- GOOS=linux GOARCH=amd64 go build -o build/noheir-api.new ./cmd/main.go
+#     - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN
+#     - docker build -t $REGISTRY_URL/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
+#     - docker push $REGISTRY_URL/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
+#   artifacts:
+#     paths:
+#       - build/noheir-api.new
+#     expire_in: 7 days
+#   rules:
+#     - if: $CI_COMMIT_BRANCH == "main"
 
-# -------------------------
-# Deploy (production)
-# -------------------------
-deploy_production:
-  stage: deploy
-  image: alpine:latest
-  timeout: 5m
-  before_script:
-    - apk add --no-cache openssh-client
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan noheir-api.duckdns.org >> ~/.ssh/known_hosts
+# # -------------------------
+# # Deploy (production)
+# # -------------------------
+# deploy_production:
+#   stage: deploy
+#   image: alpine:latest
+#   timeout: 5m
+#   before_script:
+#     - apk add --no-cache openssh-client
+#     - eval $(ssh-agent -s)
+#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+#     - mkdir -p ~/.ssh
+#     - chmod 700 ~/.ssh
+#     - ssh-keyscan noheir-api.duckdns.org >> ~/.ssh/known_hosts
 
-  script:
-    - scp build/noheir-api.new quang@noheir-api.duckdns.org:/home/quang/
-    - |
-      ssh -o ConnectTimeout=10 quang@noheir-api.duckdns.org "
-        set -e
+#   script:
+#     - scp build/noheir-api.new quang@noheir-api.duckdns.org:/home/quang/
+#     - |
+#       ssh -o ConnectTimeout=10 quang@noheir-api.duckdns.org "
+#         set -e
 
-        cd /home/quang
+#         cd /home/quang
 
-        ts=\$(date +%s)
+#         ts=\$(date +%s)
 
-        if [ -L noheir-api ]; then
-          prev=\$(readlink noheir-api)
-        else
-          prev=\"\"
-        fi
+#         if [ -L noheir-api ]; then
+#           prev=\$(readlink noheir-api)
+#         else
+#           prev=\"\"
+#         fi
 
-        mv noheir-api.new noheir-api-\$ts
-        chmod +x noheir-api-\$ts
+#         mv noheir-api.new noheir-api-\$ts
+#         chmod +x noheir-api-\$ts
 
-        ln -sfn noheir-api-\$ts noheir-api
+#         ln -sfn noheir-api-\$ts noheir-api
 
-        sudo systemctl restart noheir
+#         sudo systemctl restart noheir
 
-        for i in 1 2 3 4 5; do
-          if curl -fsS https://noheir-api.duckdns.org/health/live; then
-            break
-          fi
-          sleep 2
-        done
+#         for i in 1 2 3 4 5; do
+#           if curl -fsS https://noheir-api.duckdns.org/health/live; then
+#             break
+#           fi
+#           sleep 2
+#         done
 
-        # Final check
-        curl -fsS https://noheir-api.duckdns.org/health/live || (
-          if [ -n "$prev" ]; then
-            ln -sfn $prev noheir-api
-            sudo systemctl restart noheir
-          fi
-          exit 1
-        )
-      "
-  rules:
-    - if: $CI_COMMIT_BRANCH == "main"
+#         # Final check
+#         curl -fsS https://noheir-api.duckdns.org/health/live || (
+#           if [ -n "$prev" ]; then
+#             ln -sfn $prev noheir-api
+#             sudo systemctl restart noheir
+#           fi
+#           exit 1
+#         )
+#       "
+#   rules:
+#     - if: $CI_COMMIT_BRANCH == "main"
